package com.jrwp.payMent.dao;

import com.jrwp.payMent.entity.AppraiseModel;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AppraiseModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APPRAISE_MODEL
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APPRAISE_MODEL
     *
     * @mbggenerated
     */
    int insert(AppraiseModel record);
    int insert1(AppraiseModel record);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APPRAISE_MODEL
     *
     * @mbggenerated
     */
    int insertSelective(AppraiseModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APPRAISE_MODEL
     *
     * @mbggenerated
     */
    AppraiseModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APPRAISE_MODEL
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AppraiseModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APPRAISE_MODEL
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AppraiseModel record);
    List<AppraiseModel> list(@Param("modelName") String modelName);
    List<AppraiseModel> list1(@Param("modelName") String modelName);
}