package com.jrwp.payMent.dao;

import com.jrwp.payMent.entity.AppraiseDetail;

import java.util.List;

public interface AppraiseDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APPRAISE_DETAIL
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);
    int deleteByModelId(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APPRAISE_DETAIL
     *
     * @mbggenerated
     */
    int insert(AppraiseDetail record);
    int insert1(AppraiseDetail record);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APPRAISE_DETAIL
     *
     * @mbggenerated
     */
    int insertSelective(AppraiseDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APPRAISE_DETAIL
     *
     * @mbggenerated
     */
    AppraiseDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APPRAISE_DETAIL
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AppraiseDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APPRAISE_DETAIL
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AppraiseDetail record);
    List<AppraiseDetail> getByModelId(int id);
    List<AppraiseDetail> getDetailByModelId(int id);
    int insertIcon(AppraiseDetail appraiseDetail);
}