package com.jrwp.payMent.dao;

import com.jrwp.payMent.entity.HotelUpdate;

import java.math.BigDecimal;
import java.util.List;

public interface HotelUpdateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOTEL_UPDATE
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOTEL_UPDATE
     *
     * @mbggenerated
     */
    int insert(HotelUpdate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOTEL_UPDATE
     *
     * @mbggenerated
     */
    int insertSelective(HotelUpdate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOTEL_UPDATE
     *
     * @mbggenerated
     */
    HotelUpdate selectByPrimaryKey(BigDecimal id);
    List<HotelUpdate> list();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOTEL_UPDATE
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HotelUpdate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOTEL_UPDATE
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HotelUpdate record);
}