package com.jrwp.payMent.dao;

import com.jrwp.payMent.entity.HotelUpdateFile;
import com.jrwp.payMent.entity.UpdateItem;

import java.math.BigDecimal;
import java.util.List;

public interface HotelUpdateFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOTEL_UPDATEFILE
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOTEL_UPDATEFILE
     *
     * @mbggenerated
     */
    int insert(HotelUpdateFile record);

    List<HotelUpdateFile> list(BigDecimal id);
    List<HotelUpdateFile> selectByDllName(String dllname);
    List<UpdateItem> listbyupdateid(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOTEL_UPDATEFILE
     *
     * @mbggenerated
     */
    int insertSelective(HotelUpdateFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOTEL_UPDATEFILE
     *
     * @mbggenerated
     */
    HotelUpdateFile selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOTEL_UPDATEFILE
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HotelUpdateFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HOTEL_UPDATEFILE
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HotelUpdateFile record);
}