package com.jrwp.payMent.dao;

import com.jrwp.payMent.entity.OrderCount;
import com.jrwp.payMent.entity.PayOrderDetails;
import com.jrwp.payMent.entity.PayOrders;

import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface PayOrderDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAY_ORDERDETAILS
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAY_ORDERDETAILS
     *
     * @mbggenerated
     */
    int insert(PayOrderDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAY_ORDERDETAILS
     *
     * @mbggenerated
     */
    int insertSelective(PayOrderDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAY_ORDERDETAILS
     *
     * @mbggenerated
     */
    PayOrderDetails selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAY_ORDERDETAILS
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PayOrderDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAY_ORDERDETAILS
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PayOrderDetails record);

    PayOrderDetails getDetailsById(BigDecimal id);

    List<PayOrderDetails> getDetailsList(Long userid);
    
   
    /*
    数据统计
     */
    List<OrderCount> getOrderCount(@Param("userid") Long userid,@Param("paystatus") String paystatus, @Param("begintime") String begintime,
                                   @Param("endtime") String endtime);
    List<OrderCount> getOrderCountBydeptid(@Param("deptid") Long deptid,@Param("paystatus") String paystatus, @Param("begintime") String begintime,
                                   @Param("endtime") String endtime);
    List<OrderCount> getAllOrderCount(@Param("paystatus") String paystatus, @Param("begintime") String begintime,
                                           @Param("endtime") String endtime);
}