package com.jrwp.payMent.dao;

import com.jrwp.payMent.entity.PayOrders;
import org.apache.ibatis.annotations.Param;

import java.math.BigDecimal;
import java.util.List;

public interface PayOrdersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAY_ORDERS
     *
     * @mbggenerated
     */
    List<PayOrders> getOrderList(@Param("userid") Long userid, @Param("paystatus") String paystatus, @Param("workprocessnumber")
            String workprocessnumber, @Param("begintime") String begintime, @Param("endtime") String endtime);

    List<PayOrders> getOrderListBydeptid(@Param("deptid") Long deptid, @Param("paystatus") String paystatus, @Param
            ("workprocessnumber") String workprocessnumber, @Param("begintime") String begintime, @Param("endtime") String endtime);

    List<PayOrders> getAllOrderList(@Param("paystatus") String paystatus, @Param("workprocessnumber") String workprocessnumber,
                                    @Param("begintime") String begintime, @Param("endtime") String endtime);

    PayOrders getOrderByid(@Param("id") Long id);

    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAY_ORDERS
     *
     * @mbggenerated
     */
    int insert(PayOrders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAY_ORDERS
     *
     * @mbggenerated
     */
    int insertSelective(PayOrders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAY_ORDERS
     *
     * @mbggenerated
     */
    PayOrders selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAY_ORDERS
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PayOrders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAY_ORDERS
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PayOrders record);

    List<PayOrders> getDetailsListByTime(@Param("userid") Long userid, @Param("paystatus") String paystatus, @Param
            ("workprocessnumber") String workprocessnumber, @Param("begintime") String begintime, @Param("endtime") String endtime);

}