package com.jrwp.payMent.dao;

import com.jrwp.core.entity.Core_Dept;
import com.jrwp.payMent.entity.PayWan;
import com.jrwp.payMent.entity.PayWanInfo;
import com.jrwp.payMent.entity.WanCount;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PayWanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAY_WAN
     *
     * @mbggenerated
     */
    List<WanCount> coutwanbymachine(@Param("payType") String payType, @Param("begintime") String begintime, @Param("endtime") String
            endtime, @Param("startCodes") List<String> startCodes, @Param("macIds") Integer[] macIds);

    List<WanCount> coutwanbyconfig(@Param("payType") String payType, @Param("begintime") String begintime, @Param("endtime") String
            endtime, @Param("machinetype") Integer startCodes, @Param("configname") String configname);

    int insert(PayWan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PAY_WAN
     *
     * @mbggenerated
     */
    int insertSelective(PayWan record);

    List<PayWanInfo> listBycode(@Param("whereSql") String wheresql);

    List<PayWanInfo> getWanList(@Param("payStatus") String payStatus, @Param("payType") String payType, @Param("begintime") String
            begintime, @Param("endtime") String endtime, @Param("startCodes") List<String> startCodes, @Param("configName") String
            configName, @Param("ordernumber") String ordernumber);

    PayWanInfo getWanInfo(@Param("id") Integer id);

    PayWan getByOrderNumber(String ordernumber);

    List<Core_Dept> getMachines(@Param("deptId") Long deptId);
}