package com.jrwp.payMent.dao;

import com.jrwp.payMent.entity.UserService;

import java.util.List;

public interface UserServiceMapper {


    List<UserService> getByUsCode(String uiCode);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERSERVICE
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String usCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERSERVICE
     *
     * @mbggenerated
     */
    int insert(UserService record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERSERVICE
     *
     * @mbggenerated
     */
    int insertSelective(UserService record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERSERVICE
     *
     * @mbggenerated
     */
    UserService selectByPrimaryKey(String usCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERSERVICE
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserService record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERSERVICE
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserService record);
}