package com.jrwp.wx.entity;

import com.jrwp.core.entity.Core_Dept;

import java.util.Date;

public class AppointmeInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPOINTME_INFO.ID
     *
     * @mbggenerated
     */
    private String openid;
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPOINTME_INFO.CARDNUMBER
     *
     * @mbggenerated
     */
    private String cardnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPOINTME_INFO.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPOINTME_INFO.DEPTID
     *
     * @mbggenerated
     */
    private Integer deptid;
    private Core_Dept dept;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPOINTME_INFO.APPOINTMENTTIME
     *
     * @mbggenerated
     */
    //预约的日期
    private String appointmenttime;
    private int timeQuantum;
    //预约的时间段
    private TimeQuan timeQuan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPOINTME_INFO.STATUS
     *
     * @mbggenerated
     */
    private int status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPOINTME_INFO.PHONE
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPOINTME_INFO.CREATETIME
     *
     * @mbggenerated
     */
    private Date createtime;

    public int getTimeQuantum() {
        return timeQuantum;
    }

    public void setTimeQuantum(int timeQuantum) {
        this.timeQuantum = timeQuantum;
    }

    public TimeQuan getTimeQuan() {
        return timeQuan;
    }

    public void setTimeQuan(TimeQuan timeQuan) {
        this.timeQuan = timeQuan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPOINTME_INFO.ID
     *
     * @return the value of APPOINTME_INFO.ID
     * @mbggenerated
     */

    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPOINTME_INFO.ID
     *
     * @param id the value for APPOINTME_INFO.ID
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPOINTME_INFO.CARDNUMBER
     *
     * @return the value of APPOINTME_INFO.CARDNUMBER
     * @mbggenerated
     */
    public String getCardnumber() {
        return cardnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPOINTME_INFO.CARDNUMBER
     *
     * @param cardnumber the value for APPOINTME_INFO.CARDNUMBER
     * @mbggenerated
     */
    public void setCardnumber(String cardnumber) {
        this.cardnumber = cardnumber == null ? null : cardnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPOINTME_INFO.NAME
     *
     * @return the value of APPOINTME_INFO.NAME
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPOINTME_INFO.NAME
     *
     * @param name the value for APPOINTME_INFO.NAME
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPOINTME_INFO.DEPTID
     *
     * @return the value of APPOINTME_INFO.DEPTID
     * @mbggenerated
     */
    public Integer getDeptid() {
        return deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPOINTME_INFO.DEPTID
     *
     * @param deptid the value for APPOINTME_INFO.DEPTID
     * @mbggenerated
     */
    public void setDeptid(Integer deptid) {
        this.deptid = deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPOINTME_INFO.APPOINTMENTTIME
     *
     * @return the value of APPOINTME_INFO.APPOINTMENTTIME
     * @mbggenerated
     */
    public String getAppointmenttime() {
        return appointmenttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPOINTME_INFO.APPOINTMENTTIME
     *
     * @param appointmenttime the value for APPOINTME_INFO.APPOINTMENTTIME
     * @mbggenerated
     */
    public void setAppointmenttime(String appointmenttime) {
        this.appointmenttime = appointmenttime == null ? null : appointmenttime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPOINTME_INFO.STATUS
     *
     * @return the value of APPOINTME_INFO.STATUS
     * @mbggenerated
     */
    public int getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPOINTME_INFO.STATUS
     *
     * @param status the value for APPOINTME_INFO.STATUS
     * @mbggenerated
     */
    public void setStatus(int status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPOINTME_INFO.PHONE
     *
     * @return the value of APPOINTME_INFO.PHONE
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPOINTME_INFO.PHONE
     *
     * @param phone the value for APPOINTME_INFO.PHONE
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPOINTME_INFO.CREATETIME
     *
     * @return the value of APPOINTME_INFO.CREATETIME
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPOINTME_INFO.CREATETIME
     *
     * @param createtime the value for APPOINTME_INFO.CREATETIME
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    public String getOpenid() {
        return openid;
    }

    public void setOpenid(String openid) {
        this.openid = openid;
    }

    public Core_Dept getDept() {
        return dept;
    }

    public void setDept(Core_Dept dept) {
        this.dept = dept;
    }
}