package com.jrwp.wx.entity;

import com.jrwp.core.entity.Core_Dept;

import java.util.Date;

public class SquenceInfo {

	private Integer id;

	private int isappointment;

	private String cardnumber;

	private Integer isearly;

	private String appointmenttime;
	private Integer timeQuantum;
	// 预约的时间段
	private TimeQuan timeQuan;

	private String squence;
	private int status;
	private String openid;
	private Core_Dept dept;
	private Integer deptid;
	private String createtime;

	public Integer getTimeQuantum() {
		return timeQuantum;
	}

	public void setTimeQuantum(Integer timeQuantum) {
		this.timeQuantum = timeQuantum;
	}

	public TimeQuan getTimeQuan() {
		return timeQuan;
	}

	public void setTimeQuan(TimeQuan timeQuan) {
		this.timeQuan = timeQuan;
	}

	public String getOpenid() {
		return openid;
	}

	public void setOpenid(String openid) {
		this.openid = openid;
	}

	public Core_Dept getDept() {
		return dept;
	}

	public void setDept(Core_Dept dept) {
		this.dept = dept;
	}

	public String getSquence() {
		return squence;
	}

	public void setSquence(String squence) {
		this.squence = squence;
	}

	public int getStatus() {
		return status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column SQUENCE_INFO.ID
	 * 
	 * @param id
	 *            the value for SQUENCE_INFO.ID
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column SQUENCE_INFO.ISAPPOINTMENT
	 * 
	 * @return the value of SQUENCE_INFO.ISAPPOINTMENT
	 * @mbggenerated
	 */
	public int getIsappointment() {
		return isappointment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column SQUENCE_INFO.ISAPPOINTMENT
	 * 
	 * @param isappointment
	 *            the value for SQUENCE_INFO.ISAPPOINTMENT
	 * @mbggenerated
	 */
	public void setIsappointment(int isappointment) {
		this.isappointment = isappointment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column SQUENCE_INFO.ISEARLY
	 * 
	 * @return the value of SQUENCE_INFO.ISEARLY
	 * @mbggenerated
	 */
	public Integer getIsearly() {
		return isearly;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column SQUENCE_INFO.ISEARLY
	 * 
	 * @param isearly
	 *            the value for SQUENCE_INFO.ISEARLY
	 * @mbggenerated
	 */
	public void setIsearly(Integer isearly) {
		this.isearly = isearly;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column SQUENCE_INFO.APPOINTMENTTIME
	 * 
	 * @return the value of SQUENCE_INFO.APPOINTMENTTIME
	 * @mbggenerated
	 */
	public String getAppointmenttime() {
		return appointmenttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column SQUENCE_INFO.APPOINTMENTTIME
	 * 
	 * @param appointmenttime
	 *            the value for SQUENCE_INFO.APPOINTMENTTIME
	 * @mbggenerated
	 */
	public void setAppointmenttime(String appointmenttime) {
		this.appointmenttime = appointmenttime == null ? null : appointmenttime
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column SQUENCE_INFO.SQUENCE
	 * 
	 * @return the value of SQUENCE_INFO.SQUENCE
	 * @mbggenerated
	 */

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column SQUENCE_INFO.SQUENCE
	 * 
	 * @param squence
	 *            the value for SQUENCE_INFO.SQUENCE
	 * @mbggenerated
	 */

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column SQUENCE_INFO.DEPTID
	 * 
	 * @return the value of SQUENCE_INFO.DEPTID
	 * @mbggenerated
	 */
	public Integer getDeptid() {
		return deptid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column SQUENCE_INFO.DEPTID
	 * 
	 * @param deptid
	 *            the value for SQUENCE_INFO.DEPTID
	 * @mbggenerated
	 */
	public void setDeptid(Integer deptid) {
		this.deptid = deptid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column SQUENCE_INFO.CREATETIME
	 * 
	 * @return the value of SQUENCE_INFO.CREATETIME
	 * @mbggenerated
	 */
	public String getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column SQUENCE_INFO.CREATETIME
	 * 
	 * @param createtime
	 *            the value for SQUENCE_INFO.CREATETIME
	 * @mbggenerated
	 */
	public void setCreatetime(String createtime) {
		this.createtime = createtime;
	}

	public String getCardnumber() {
		return cardnumber;
	}

	public void setCardnumber(String cardnumber) {
		this.cardnumber = cardnumber;
	}
}