package com.jrwp.payMent.entity;

import java.util.Date;

public class AppraiseModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPRAISE_MODEL.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPRAISE_MODEL.MODELNAME
     *
     * @mbggenerated
     */
    private String modelname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPRAISE_MODEL.CREATEUSER
     *
     * @mbggenerated
     */
    private Integer createuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPRAISE_MODEL.CREATETIME
     *
     * @mbggenerated
     */
    private Date createtime;
    private Date updatetime;
    private Integer outtime;
    private Boolean isautoappraise;
    private int isQuestionnaire;
    private Boolean iswechat;
    private Boolean iswarn;
    private Boolean wewarn;
    private Boolean haswarn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPRAISE_MODEL.ID
     *
     * @return the value of APPRAISE_MODEL.ID
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPRAISE_MODEL.ID
     *
     * @param id the value for APPRAISE_MODEL.ID
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPRAISE_MODEL.MODELNAME
     *
     * @return the value of APPRAISE_MODEL.MODELNAME
     * @mbggenerated
     */
    public String getModelname() {
        return modelname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPRAISE_MODEL.MODELNAME
     *
     * @param modelname the value for APPRAISE_MODEL.MODELNAME
     * @mbggenerated
     */
    public void setModelname(String modelname) {
        this.modelname = modelname == null ? null : modelname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPRAISE_MODEL.CREATEUSER
     *
     * @return the value of APPRAISE_MODEL.CREATEUSER
     * @mbggenerated
     */
    public Integer getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPRAISE_MODEL.CREATEUSER
     *
     * @param createuser the value for APPRAISE_MODEL.CREATEUSER
     * @mbggenerated
     */
    public void setCreateuser(Integer createuser) {
        this.createuser = createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPRAISE_MODEL.CREATETIME
     *
     * @return the value of APPRAISE_MODEL.CREATETIME
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPRAISE_MODEL.CREATETIME
     *
     * @param createtime the value for APPRAISE_MODEL.CREATETIME
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    public Date getUpdatetime() {
        return updatetime;
    }

    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    public Integer getOuttime() {
        return outtime;
    }

    public void setOuttime(Integer outtime) {
        this.outtime = outtime;
    }

    public Boolean getIsautoappraise() {
        return isautoappraise;
    }

    public void setIsautoappraise(Boolean isautoappraise) {
        this.isautoappraise = isautoappraise;
    }

    public Boolean getIswechat() {
        return iswechat;
    }

    public void setIswechat(Boolean iswechat) {
        this.iswechat = iswechat;
    }

    public Boolean getIswarn() {
        return iswarn;
    }

    public void setIswarn(Boolean iswarn) {
        this.iswarn = iswarn;
    }

    public Boolean getWewarn() {
        return wewarn;
    }

    public void setWewarn(Boolean wewarn) {
        this.wewarn = wewarn;
    }

    public Boolean getHaswarn() {
        return haswarn;
    }

    public void setHaswarn(Boolean haswarn) {
        this.haswarn = haswarn;
    }

    public int getIsQuestionnaire() {
        return isQuestionnaire;
    }

    public void setIsQuestionnaire(int isQuestionnaire) {
        this.isQuestionnaire = isQuestionnaire;
    }
}