package com.jrwp.payMent.entity;

import org.apache.shiro.codec.Base64;

public class AppraiseDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPRAISE_DETAIL.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPRAISE_DETAIL.APPRAISEMODELID
     *
     * @mbggenerated
     */
    private Integer appraisemodelid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPRAISE_DETAIL.APPRAISENAME
     *
     * @mbggenerated
     */
    private String appraisename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APPRAISE_DETAIL.APPRAISEVALUE
     *
     * @mbggenerated
     */
    private Integer appraisevalue;

    //图标
    private String iconpath;
    private byte[] icon;
    //是否为默认节点
    private Boolean isdefault;
    //Base64字符串
    private String base64_val;
//    是否包含文件
    private int isFile;
    //窗口还是微信节点
    private Boolean iswechat;
    private Boolean iswarning;
    private Boolean iswewarning;


    public String getIconpath() {
        return iconpath;
    }

    public void setIconpath(String iconpath) {
        this.iconpath = iconpath;
    }

    public byte[] getIcon() {
        return icon;
    }

    public void setIcon(byte[] icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPRAISE_DETAIL.ID
     *
     * @return the value of APPRAISE_DETAIL.ID
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPRAISE_DETAIL.ID
     *
     * @param id the value for APPRAISE_DETAIL.ID
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPRAISE_DETAIL.APPRAISEMODELID
     *
     * @return the value of APPRAISE_DETAIL.APPRAISEMODELID
     * @mbggenerated
     */
    public Integer getAppraisemodelid() {
        return appraisemodelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPRAISE_DETAIL.APPRAISEMODELID
     *
     * @param appraisemodelid the value for APPRAISE_DETAIL.APPRAISEMODELID
     * @mbggenerated
     */
    public void setAppraisemodelid(Integer appraisemodelid) {
        this.appraisemodelid = appraisemodelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPRAISE_DETAIL.APPRAISENAME
     *
     * @return the value of APPRAISE_DETAIL.APPRAISENAME
     * @mbggenerated
     */
    public String getAppraisename() {
        return appraisename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPRAISE_DETAIL.APPRAISENAME
     *
     * @param appraisename the value for APPRAISE_DETAIL.APPRAISENAME
     * @mbggenerated
     */
    public void setAppraisename(String appraisename) {
        this.appraisename = appraisename == null ? null : appraisename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APPRAISE_DETAIL.APPRAISEVALUE
     *
     * @return the value of APPRAISE_DETAIL.APPRAISEVALUE
     * @mbggenerated
     */
    public Integer getAppraisevalue() {
        return appraisevalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APPRAISE_DETAIL.APPRAISEVALUE
     *
     * @param appraisevalue the value for APPRAISE_DETAIL.APPRAISEVALUE
     * @mbggenerated
     */
    public void setAppraisevalue(Integer appraisevalue) {
        this.appraisevalue = appraisevalue;
    }

    public Boolean getIsdefault() {
        return isdefault;
    }

    public void setIsdefault(Boolean isdefault) {
        this.isdefault = isdefault;
    }

    public String getBase64_val() {
        if (base64_val != null) {
            return Base64.encodeToString(icon);
        } else {
            return "";
        }
    }

    public void setBase64_val(String base64_val) {
        this.base64_val = base64_val;
    }

    public int getIsFile() {
        return isFile;
    }

    public void setIsFile(int isFile) {
        this.isFile = isFile;
    }

    public Boolean getIswechat() {
        return iswechat;
    }

    public void setIswechat(Boolean iswechat) {
        this.iswechat = iswechat;
    }

    public Boolean getIswarning() {
        return iswarning;
    }

    public void setIswarning(Boolean iswarning) {
        this.iswarning = iswarning;
    }

    public Boolean getIswewarning() {
        return iswewarning;
    }

    public void setIswewarning(Boolean iswewarning) {
        this.iswewarning = iswewarning;
    }

}