package com.jrwp.payMent.entity;

import java.math.BigDecimal;

public class HotelUpdate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HOTEL_UPDATE.ID
     *
     * @mbggenerated
     */
    private BigDecimal id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HOTEL_UPDATE.UPLOADNAME
     *
     * @mbggenerated
     */
    private String uploadname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HOTEL_UPDATE.DLLNAME
     *
     * @mbggenerated
     */
    private String dllname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HOTEL_UPDATE.WORKTYPE
     *
     * @mbggenerated
     */
    private Short worktype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HOTEL_UPDATE.ID
     *
     * @return the value of HOTEL_UPDATE.ID
     *
     * @mbggenerated
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HOTEL_UPDATE.ID
     *
     * @param id the value for HOTEL_UPDATE.ID
     *
     * @mbggenerated
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HOTEL_UPDATE.UPLOADNAME
     *
     * @return the value of HOTEL_UPDATE.UPLOADNAME
     *
     * @mbggenerated
     */
    public String getUploadname() {
        return uploadname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HOTEL_UPDATE.UPLOADNAME
     *
     * @param uploadname the value for HOTEL_UPDATE.UPLOADNAME
     *
     * @mbggenerated
     */
    public void setUploadname(String uploadname) {
        this.uploadname = uploadname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HOTEL_UPDATE.DLLNAME
     *
     * @return the value of HOTEL_UPDATE.DLLNAME
     *
     * @mbggenerated
     */
    public String getDllname() {
        return dllname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HOTEL_UPDATE.DLLNAME
     *
     * @param dllname the value for HOTEL_UPDATE.DLLNAME
     *
     * @mbggenerated
     */
    public void setDllname(String dllname) {
        this.dllname = dllname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HOTEL_UPDATE.WORKTYPE
     *
     * @return the value of HOTEL_UPDATE.WORKTYPE
     *
     * @mbggenerated
     */
    public Short getWorktype() {
        return worktype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HOTEL_UPDATE.WORKTYPE
     *
     * @param worktype the value for HOTEL_UPDATE.WORKTYPE
     *
     * @mbggenerated
     */
    public void setWorktype(Short worktype) {
        this.worktype = worktype;
    }
}