package com.jrwp.payMent.entity;

import java.math.BigDecimal;

public class HotelUpdateFile {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HOTEL_UPDATEFILE.ID
     *
     * @mbggenerated
     */
    private BigDecimal id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HOTEL_UPDATEFILE.UPDATEID
     *
     * @mbggenerated
     */
    private BigDecimal updateid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HOTEL_UPDATEFILE.DOWNLOADPATH
     *
     * @mbggenerated
     */
    private String downloadpath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HOTEL_UPDATEFILE.VERSION
     *
     * @mbggenerated
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HOTEL_UPDATEFILE.ISVERSION
     *
     * @mbggenerated
     */
    private Short isversion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HOTEL_UPDATEFILE.CLIENTCOPYPATH
     *
     * @mbggenerated
     */
    private String clientcopypath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HOTEL_UPDATEFILE.ISSTART
     *
     * @mbggenerated
     */
    private Short isstart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HOTEL_UPDATEFILE.DLLNAME
     *
     * @mbggenerated
     */
    private String dllname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HOTEL_UPDATEFILE.ID
     *
     * @return the value of HOTEL_UPDATEFILE.ID
     *
     * @mbggenerated
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HOTEL_UPDATEFILE.ID
     *
     * @param id the value for HOTEL_UPDATEFILE.ID
     *
     * @mbggenerated
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HOTEL_UPDATEFILE.UPDATEID
     *
     * @return the value of HOTEL_UPDATEFILE.UPDATEID
     *
     * @mbggenerated
     */
    public BigDecimal getUpdateid() {
        return updateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HOTEL_UPDATEFILE.UPDATEID
     *
     * @param updateid the value for HOTEL_UPDATEFILE.UPDATEID
     *
     * @mbggenerated
     */
    public void setUpdateid(BigDecimal updateid) {
        this.updateid = updateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HOTEL_UPDATEFILE.DOWNLOADPATH
     *
     * @return the value of HOTEL_UPDATEFILE.DOWNLOADPATH
     *
     * @mbggenerated
     */
    public String getDownloadpath() {
        return downloadpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HOTEL_UPDATEFILE.DOWNLOADPATH
     *
     * @param downloadpath the value for HOTEL_UPDATEFILE.DOWNLOADPATH
     *
     * @mbggenerated
     */
    public void setDownloadpath(String downloadpath) {
        this.downloadpath = downloadpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HOTEL_UPDATEFILE.VERSION
     *
     * @return the value of HOTEL_UPDATEFILE.VERSION
     *
     * @mbggenerated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HOTEL_UPDATEFILE.VERSION
     *
     * @param version the value for HOTEL_UPDATEFILE.VERSION
     *
     * @mbggenerated
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HOTEL_UPDATEFILE.ISVERSION
     *
     * @return the value of HOTEL_UPDATEFILE.ISVERSION
     *
     * @mbggenerated
     */
    public Short getIsversion() {
        return isversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HOTEL_UPDATEFILE.ISVERSION
     *
     * @param isversion the value for HOTEL_UPDATEFILE.ISVERSION
     *
     * @mbggenerated
     */
    public void setIsversion(Short isversion) {
        this.isversion = isversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HOTEL_UPDATEFILE.CLIENTCOPYPATH
     *
     * @return the value of HOTEL_UPDATEFILE.CLIENTCOPYPATH
     *
     * @mbggenerated
     */
    public String getClientcopypath() {
        return clientcopypath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HOTEL_UPDATEFILE.CLIENTCOPYPATH
     *
     * @param clientcopypath the value for HOTEL_UPDATEFILE.CLIENTCOPYPATH
     *
     * @mbggenerated
     */
    public void setClientcopypath(String clientcopypath) {
        this.clientcopypath = clientcopypath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HOTEL_UPDATEFILE.ISSTART
     *
     * @return the value of HOTEL_UPDATEFILE.ISSTART
     *
     * @mbggenerated
     */
    public Short getIsstart() {
        return isstart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HOTEL_UPDATEFILE.ISSTART
     *
     * @param isstart the value for HOTEL_UPDATEFILE.ISSTART
     *
     * @mbggenerated
     */
    public void setIsstart(Short isstart) {
        this.isstart = isstart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HOTEL_UPDATEFILE.DLLNAME
     *
     * @return the value of HOTEL_UPDATEFILE.DLLNAME
     *
     * @mbggenerated
     */
    public String getDllname() {
        return dllname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HOTEL_UPDATEFILE.DLLNAME
     *
     * @param dllname the value for HOTEL_UPDATEFILE.DLLNAME
     *
     * @mbggenerated
     */
    public void setDllname(String dllname) {
        this.dllname = dllname;
    }
}