package com.jrwp.payMent.entity;

import java.math.BigDecimal;

public class PayOrderDetails {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PAY_ORDERDETAILS.ID
     *
     * @mbggenerated
     */
    private BigDecimal id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PAY_ORDERDETAILS.ORDERID
     *
     * @mbggenerated
     */
    private BigDecimal orderid;
    //   private PayOrders orderInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PAY_ORDERDETAILS.WORKCORDE
     *
     * @mbggenerated
     */
    private Object workcorde;

    private PoliceClassService policeClassService;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PAY_ORDERDETAILS.WORKPROCESSNUMBER
     *
     * @mbggenerated
     */
    private Object workprocessnumber;
    private Integer iswrite;
    private Double paymoney;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PAY_ORDERDETAILS.ID
     *
     * @return the value of PAY_ORDERDETAILS.ID
     * @mbggenerated
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PAY_ORDERDETAILS.ID
     *
     * @param id the value for PAY_ORDERDETAILS.ID
     * @mbggenerated
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PAY_ORDERDETAILS.ORDERID
     *
     * @return the value of PAY_ORDERDETAILS.ORDERID
     * @mbggenerated
     */
    public BigDecimal getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PAY_ORDERDETAILS.ORDERID
     *
     * @param orderid the value for PAY_ORDERDETAILS.ORDERID
     * @mbggenerated
     */
    public void setOrderid(BigDecimal orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PAY_ORDERDETAILS.WORKCORDE
     *
     * @return the value of PAY_ORDERDETAILS.WORKCORDE
     * @mbggenerated
     */
    public Object getWorkcorde() {
        return workcorde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PAY_ORDERDETAILS.WORKCORDE
     *
     * @param workcorde the value for PAY_ORDERDETAILS.WORKCORDE
     * @mbggenerated
     */
    public void setWorkcorde(Object workcorde) {
        this.workcorde = workcorde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PAY_ORDERDETAILS.WORKPROCESSNUMBER
     *
     * @return the value of PAY_ORDERDETAILS.WORKPROCESSNUMBER
     * @mbggenerated
     */
    public Object getWorkprocessnumber() {
        return workprocessnumber;
    }


    public void setWorkprocessnumber(Object workprocessnumber) {
        this.workprocessnumber = workprocessnumber;
    }

//    public PayOrders getOrderInfo() {
//        return orderInfo;
//    }

//    public void setOrderInfo(PayOrders orderInfo) {
//        this.orderInfo = orderInfo;
//    }

    public PoliceClassService getPoliceClassService() {
        return policeClassService;
    }

    public void setPoliceClassService(PoliceClassService policeClassService) {
        this.policeClassService = policeClassService;
    }

    public Double getPaymoney() {
        return paymoney;
    }

    public void setPaymoney(Double paymoney) {
        this.paymoney = paymoney;
    }

    public Integer getIswrite() {
        return iswrite;
    }

    public void setIswrite(Integer iswrite) {
        this.iswrite = iswrite;
    }
}