package com.jrwp.payMent.entity;

import com.jrwp.core.entity.Core_User;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

public class PayOrders {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PAY_ORDERS.ID
     *
     * @mbggenerated
     */
    private BigDecimal id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PAY_ORDERS.USERID
     *
     * @mbggenerated
     */
    private BigDecimal userid;
    private Core_User user;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PAY_ORDERS.MACHINECORE
     *
     * @mbggenerated
     */
    private Object machinecore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PAY_ORDERS.MACHINEIP
     *
     * @mbggenerated
     */
    private Object machineip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PAY_ORDERS.PAYTYPE
     *
     * @mbggenerated
     */
    private Short paytype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PAY_ORDERS.PAYSTATUS
     *
     * @mbggenerated
     */
    private Short paystatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PAY_ORDERS.PAYMONEY
     *
     * @mbggenerated
     */
    private BigDecimal paymoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PAY_ORDERS.CREATTIME
     *
     * @mbggenerated
     */
    private String creattime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PAY_ORDERS.PAYIDFORWX
     *
     * @mbggenerated
     */
    private BigDecimal payidforwx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PAY_ORDERS.QRCODEURLFORWX
     *
     * @mbggenerated
     */
    private Object qrcodeurlforwx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PAY_ORDERS.PAYIDFORALI
     *
     * @mbggenerated
     */
    private BigDecimal payidforali;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PAY_ORDERS.QRCODEURLFORALI
     *
     * @mbggenerated
     */
    private Object qrcodeurlforali;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PAY_ORDERS.RELPAYTYPE
     *
     * @mbggenerated
     */
    private Short relpaytype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PAY_ORDERS.ORDERNUMBER
     *
     * @mbggenerated
     */
    private Object ordernumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PAY_ORDERS.PAYTIME
     *
     * @mbggenerated
     */
    private String paytime;


    private List<PayOrderDetails> orderDetails;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PAY_ORDERS.ID
     *
     * @return the value of PAY_ORDERS.ID
     *
     * @mbggenerated
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PAY_ORDERS.ID
     *
     * @param id the value for PAY_ORDERS.ID
     *
     * @mbggenerated
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PAY_ORDERS.USERID
     *
     * @return the value of PAY_ORDERS.USERID
     *
     * @mbggenerated
     */
    public BigDecimal getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PAY_ORDERS.USERID
     *
     * @param userid the value for PAY_ORDERS.USERID
     *
     * @mbggenerated
     */
    public void setUserid(BigDecimal userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PAY_ORDERS.MACHINECORE
     *
     * @return the value of PAY_ORDERS.MACHINECORE
     *
     * @mbggenerated
     */
    public Object getMachinecore() {
        return machinecore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PAY_ORDERS.MACHINECORE
     *
     * @param machinecore the value for PAY_ORDERS.MACHINECORE
     *
     * @mbggenerated
     */
    public void setMachinecore(Object machinecore) {
        this.machinecore = machinecore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PAY_ORDERS.MACHINEIP
     *
     * @return the value of PAY_ORDERS.MACHINEIP
     *
     * @mbggenerated
     */
    public Object getMachineip() {
        return machineip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PAY_ORDERS.MACHINEIP
     *
     * @param machineip the value for PAY_ORDERS.MACHINEIP
     *
     * @mbggenerated
     */
    public void setMachineip(Object machineip) {
        this.machineip = machineip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PAY_ORDERS.PAYTYPE
     *
     * @return the value of PAY_ORDERS.PAYTYPE
     *
     * @mbggenerated
     */
    public Short getPaytype() {
        return paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PAY_ORDERS.PAYTYPE
     *
     * @param paytype the value for PAY_ORDERS.PAYTYPE
     *
     * @mbggenerated
     */
    public void setPaytype(Short paytype) {
        this.paytype = paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PAY_ORDERS.PAYSTATUS
     *
     * @return the value of PAY_ORDERS.PAYSTATUS
     *
     * @mbggenerated
     */
    public Short getPaystatus() {
        return paystatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PAY_ORDERS.PAYSTATUS
     *
     * @param paystatus the value for PAY_ORDERS.PAYSTATUS
     *
     * @mbggenerated
     */
    public void setPaystatus(Short paystatus) {
        this.paystatus = paystatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PAY_ORDERS.PAYMONEY
     *
     * @return the value of PAY_ORDERS.PAYMONEY
     *
     * @mbggenerated
     */
    public BigDecimal getPaymoney() {
        return paymoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PAY_ORDERS.PAYMONEY
     *
     * @param paymoney the value for PAY_ORDERS.PAYMONEY
     *
     * @mbggenerated
     */
    public void setPaymoney(BigDecimal paymoney) {
        this.paymoney = paymoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PAY_ORDERS.CREATTIME
     *
     * @return the value of PAY_ORDERS.CREATTIME
     *
     *
     */
    public String getCreattime() {


        return creattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PAY_ORDERS.CREATTIME
     *
     * @param creattime the value for PAY_ORDERS.CREATTIME
     *
     *
     */
    public void setCreattime(String creattime) {
        this.creattime = creattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PAY_ORDERS.PAYIDFORWX
     *
     * @return the value of PAY_ORDERS.PAYIDFORWX
     *
     *
     */
    public BigDecimal getPayidforwx() {
        return payidforwx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PAY_ORDERS.PAYIDFORWX
     *
     * @param payidforwx the value for PAY_ORDERS.PAYIDFORWX
     *
     * @mbggenerated
     */
    public void setPayidforwx(BigDecimal payidforwx) {
        this.payidforwx = payidforwx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PAY_ORDERS.QRCODEURLFORWX
     *
     * @return the value of PAY_ORDERS.QRCODEURLFORWX
     *
     * @mbggenerated
     */
    public Object getQrcodeurlforwx() {
        return qrcodeurlforwx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PAY_ORDERS.QRCODEURLFORWX
     *
     * @param qrcodeurlforwx the value for PAY_ORDERS.QRCODEURLFORWX
     *
     * @mbggenerated
     */
    public void setQrcodeurlforwx(Object qrcodeurlforwx) {
        this.qrcodeurlforwx = qrcodeurlforwx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PAY_ORDERS.PAYIDFORALI
     *
     * @return the value of PAY_ORDERS.PAYIDFORALI
     *
     * @mbggenerated
     */
    public BigDecimal getPayidforali() {
        return payidforali;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PAY_ORDERS.PAYIDFORALI
     *
     * @param payidforali the value for PAY_ORDERS.PAYIDFORALI
     *
     * @mbggenerated
     */
    public void setPayidforali(BigDecimal payidforali) {
        this.payidforali = payidforali;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PAY_ORDERS.QRCODEURLFORALI
     *
     * @return the value of PAY_ORDERS.QRCODEURLFORALI
     *
     * @mbggenerated
     */
    public Object getQrcodeurlforali() {
        return qrcodeurlforali;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PAY_ORDERS.QRCODEURLFORALI
     *
     * @param qrcodeurlforali the value for PAY_ORDERS.QRCODEURLFORALI
     *
     * @mbggenerated
     */
    public void setQrcodeurlforali(Object qrcodeurlforali) {
        this.qrcodeurlforali = qrcodeurlforali;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PAY_ORDERS.RELPAYTYPE
     *
     * @return the value of PAY_ORDERS.RELPAYTYPE
     *
     * @mbggenerated
     */
    public Short getRelpaytype() {
        return relpaytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PAY_ORDERS.RELPAYTYPE
     *
     * @param relpaytype the value for PAY_ORDERS.RELPAYTYPE
     *
     * @mbggenerated
     */
    public void setRelpaytype(Short relpaytype) {
        this.relpaytype = relpaytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PAY_ORDERS.ORDERNUMBER
     *
     * @return the value of PAY_ORDERS.ORDERNUMBER
     *
     * @mbggenerated
     */
    public Object getOrdernumber() {
        return ordernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PAY_ORDERS.ORDERNUMBER
     *
     * @param ordernumber the value for PAY_ORDERS.ORDERNUMBER
     *
     * @mbggenerated
     */
    public void setOrdernumber(Object ordernumber) {
        this.ordernumber = ordernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PAY_ORDERS.PAYTIME
     *
     * @return the value of PAY_ORDERS.PAYTIME
     *
     * @mbggenerated
     */
    public String getPaytime() {
        return paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PAY_ORDERS.PAYTIME
     *
     * @param paytime the value for PAY_ORDERS.PAYTIME
     *
     * @mbggenerated
     */
    public void setPaytime(String paytime) {
        this.paytime = paytime;
    }

    public Core_User getUser() {
        return user;
    }

    public void setUser(Core_User user) {
        this.user = user;
    }

    public List<PayOrderDetails> getOrderDetails() {
        return orderDetails;
    }

    public void setOrderDetails(List<PayOrderDetails> orderDetails) {
        this.orderDetails = orderDetails;
    }
}