package com.jrwp.payMent.entity;

import java.math.BigDecimal;
import java.util.Date;

public class PayWan {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PAY_WAN.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PAY_WAN.WORKID
     *
     * @mbggenerated
     */
    private Object workid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PAY_WAN.IDNUMBER
     *
     * @mbggenerated
     */
    private Object idnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PAY_WAN.MACHINEID
     *
     * @mbggenerated
     */
    private Object machineid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PAY_WAN.MACHINETYPE
     *
     * @mbggenerated
     */
    private Short machinetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PAY_WAN.PAYMONEY
     *
     * @mbggenerated
     */
    private BigDecimal paymoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PAY_WAN.PAYTYPE
     *
     * @mbggenerated
     */
    private Short paytype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PAY_WAN.PAYSTATUS
     *
     * @mbggenerated
     */
    private Short paystatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PAY_WAN.CREATETIME
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PAY_WAN.PAYTIME
     *
     * @mbggenerated
     */
    private Date paytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PAY_WAN.ISEXPORT
     *
     * @mbggenerated
     */
    private Short isexport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PAY_WAN.PAYID
     *
     * @mbggenerated
     */
    private BigDecimal payid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PAY_WAN.QRCODETYPE
     *
     * @mbggenerated
     */
    private Short qrcodetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PAY_WAN.ORDERNUMBER
     *
     * @mbggenerated
     */
    private Object ordernumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PAY_WAN.QRCODEURL
     *
     * @mbggenerated
     */
    private Object qrcodeurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PAY_WAN.DEPTCODE
     *
     * @mbggenerated
     */
    private Object deptcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PAY_WAN.ORDERDESCRIBE
     *
     * @mbggenerated
     */
    private Object orderdescribe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PAY_WAN.ONLYIN
     *
     * @mbggenerated
     */
    private Short onlyin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PAY_WAN.QRCODE
     *
     * @mbggenerated
     */
    private byte[] qrcode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PAY_WAN.ID
     *
     * @return the value of PAY_WAN.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PAY_WAN.ID
     *
     * @param id the value for PAY_WAN.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PAY_WAN.WORKID
     *
     * @return the value of PAY_WAN.WORKID
     *
     * @mbggenerated
     */
    public Object getWorkid() {
        return workid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PAY_WAN.WORKID
     *
     * @param workid the value for PAY_WAN.WORKID
     *
     * @mbggenerated
     */
    public void setWorkid(Object workid) {
        this.workid = workid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PAY_WAN.IDNUMBER
     *
     * @return the value of PAY_WAN.IDNUMBER
     *
     * @mbggenerated
     */
    public Object getIdnumber() {
        return idnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PAY_WAN.IDNUMBER
     *
     * @param idnumber the value for PAY_WAN.IDNUMBER
     *
     * @mbggenerated
     */
    public void setIdnumber(Object idnumber) {
        this.idnumber = idnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PAY_WAN.MACHINEID
     *
     * @return the value of PAY_WAN.MACHINEID
     *
     * @mbggenerated
     */
    public Object getMachineid() {
        return machineid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PAY_WAN.MACHINEID
     *
     * @param machineid the value for PAY_WAN.MACHINEID
     *
     * @mbggenerated
     */
    public void setMachineid(Object machineid) {
        this.machineid = machineid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PAY_WAN.MACHINETYPE
     *
     * @return the value of PAY_WAN.MACHINETYPE
     *
     * @mbggenerated
     */
    public Short getMachinetype() {
        return machinetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PAY_WAN.MACHINETYPE
     *
     * @param machinetype the value for PAY_WAN.MACHINETYPE
     *
     * @mbggenerated
     */
    public void setMachinetype(Short machinetype) {
        this.machinetype = machinetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PAY_WAN.PAYMONEY
     *
     * @return the value of PAY_WAN.PAYMONEY
     *
     * @mbggenerated
     */
    public BigDecimal getPaymoney() {
        return paymoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PAY_WAN.PAYMONEY
     *
     * @param paymoney the value for PAY_WAN.PAYMONEY
     *
     * @mbggenerated
     */
    public void setPaymoney(BigDecimal paymoney) {
        this.paymoney = paymoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PAY_WAN.PAYTYPE
     *
     * @return the value of PAY_WAN.PAYTYPE
     *
     * @mbggenerated
     */
    public Short getPaytype() {
        return paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PAY_WAN.PAYTYPE
     *
     * @param paytype the value for PAY_WAN.PAYTYPE
     *
     * @mbggenerated
     */
    public void setPaytype(Short paytype) {
        this.paytype = paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PAY_WAN.PAYSTATUS
     *
     * @return the value of PAY_WAN.PAYSTATUS
     *
     * @mbggenerated
     */
    public Short getPaystatus() {
        return paystatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PAY_WAN.PAYSTATUS
     *
     * @param paystatus the value for PAY_WAN.PAYSTATUS
     *
     * @mbggenerated
     */
    public void setPaystatus(Short paystatus) {
        this.paystatus = paystatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PAY_WAN.CREATETIME
     *
     * @return the value of PAY_WAN.CREATETIME
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PAY_WAN.CREATETIME
     *
     * @param createtime the value for PAY_WAN.CREATETIME
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PAY_WAN.PAYTIME
     *
     * @return the value of PAY_WAN.PAYTIME
     *
     * @mbggenerated
     */
    public Date getPaytime() {
        return paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PAY_WAN.PAYTIME
     *
     * @param paytime the value for PAY_WAN.PAYTIME
     *
     * @mbggenerated
     */
    public void setPaytime(Date paytime) {
        this.paytime = paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PAY_WAN.ISEXPORT
     *
     * @return the value of PAY_WAN.ISEXPORT
     *
     * @mbggenerated
     */
    public Short getIsexport() {
        return isexport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PAY_WAN.ISEXPORT
     *
     * @param isexport the value for PAY_WAN.ISEXPORT
     *
     * @mbggenerated
     */
    public void setIsexport(Short isexport) {
        this.isexport = isexport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PAY_WAN.PAYID
     *
     * @return the value of PAY_WAN.PAYID
     *
     * @mbggenerated
     */
    public BigDecimal getPayid() {
        return payid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PAY_WAN.PAYID
     *
     * @param payid the value for PAY_WAN.PAYID
     *
     * @mbggenerated
     */
    public void setPayid(BigDecimal payid) {
        this.payid = payid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PAY_WAN.QRCODETYPE
     *
     * @return the value of PAY_WAN.QRCODETYPE
     *
     * @mbggenerated
     */
    public Short getQrcodetype() {
        return qrcodetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PAY_WAN.QRCODETYPE
     *
     * @param qrcodetype the value for PAY_WAN.QRCODETYPE
     *
     * @mbggenerated
     */
    public void setQrcodetype(Short qrcodetype) {
        this.qrcodetype = qrcodetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PAY_WAN.ORDERNUMBER
     *
     * @return the value of PAY_WAN.ORDERNUMBER
     *
     * @mbggenerated
     */
    public Object getOrdernumber() {
        return ordernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PAY_WAN.ORDERNUMBER
     *
     * @param ordernumber the value for PAY_WAN.ORDERNUMBER
     *
     * @mbggenerated
     */
    public void setOrdernumber(Object ordernumber) {
        this.ordernumber = ordernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PAY_WAN.QRCODEURL
     *
     * @return the value of PAY_WAN.QRCODEURL
     *
     * @mbggenerated
     */
    public Object getQrcodeurl() {
        return qrcodeurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PAY_WAN.QRCODEURL
     *
     * @param qrcodeurl the value for PAY_WAN.QRCODEURL
     *
     * @mbggenerated
     */
    public void setQrcodeurl(Object qrcodeurl) {
        this.qrcodeurl = qrcodeurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PAY_WAN.DEPTCODE
     *
     * @return the value of PAY_WAN.DEPTCODE
     *
     * @mbggenerated
     */
    public Object getDeptcode() {
        return deptcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PAY_WAN.DEPTCODE
     *
     * @param deptcode the value for PAY_WAN.DEPTCODE
     *
     * @mbggenerated
     */
    public void setDeptcode(Object deptcode) {
        this.deptcode = deptcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PAY_WAN.ORDERDESCRIBE
     *
     * @return the value of PAY_WAN.ORDERDESCRIBE
     *
     * @mbggenerated
     */
    public Object getOrderdescribe() {
        return orderdescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PAY_WAN.ORDERDESCRIBE
     *
     * @param orderdescribe the value for PAY_WAN.ORDERDESCRIBE
     *
     * @mbggenerated
     */
    public void setOrderdescribe(Object orderdescribe) {
        this.orderdescribe = orderdescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PAY_WAN.ONLYIN
     *
     * @return the value of PAY_WAN.ONLYIN
     *
     * @mbggenerated
     */
    public Short getOnlyin() {
        return onlyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PAY_WAN.ONLYIN
     *
     * @param onlyin the value for PAY_WAN.ONLYIN
     *
     * @mbggenerated
     */
    public void setOnlyin(Short onlyin) {
        this.onlyin = onlyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PAY_WAN.QRCODE
     *
     * @return the value of PAY_WAN.QRCODE
     *
     * @mbggenerated
     */
    public byte[] getQrcode() {
        return qrcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PAY_WAN.QRCODE
     *
     * @param qrcode the value for PAY_WAN.QRCODE
     *
     * @mbggenerated
     */
    public void setQrcode(byte[] qrcode) {
        this.qrcode = qrcode;
    }
}