package com.jrwp.payMent.entity;

import org.apache.shiro.codec.Base64;

import java.util.Date;

public class PhotosAndVideos {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PHOTOSANDVIDEOS.ID
	 * 
	 * @mbggenerated
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PHOTOSANDVIDEOS.VIDEO
	 * 
	 * @mbggenerated
	 */
	private String video;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PHOTOSANDVIDEOS.SEQUENCE
	 * 
	 * @mbggenerated
	 */
	private Integer sequence;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PHOTOSANDVIDEOS.CONFIGID
	 * 
	 * @mbggenerated
	 */
	private Integer configid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PHOTOSANDVIDEOS.ISVIDEOORPHOTO
	 * 
	 * @mbggenerated
	 */
	private Integer isvideoorphoto;
	private String imgval;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PHOTOSANDVIDEOS.UPDATETIME
	 * 
	 * @mbggenerated
	 */
	private Date updatetime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PHOTOSANDVIDEOS.USERID
	 * 
	 * @mbggenerated
	 */
	private Integer userid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column PHOTOSANDVIDEOS.PHOTO
	 * 
	 * @mbggenerated
	 */
	private byte[] photo;
	private String title;
	private int deptid;
	private String localURL;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PHOTOSANDVIDEOS.ID
	 * 
	 * @return the value of PHOTOSANDVIDEOS.ID
	 * 
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PHOTOSANDVIDEOS.ID
	 * 
	 * @param id
	 *            the value for PHOTOSANDVIDEOS.ID
	 * 
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PHOTOSANDVIDEOS.VIDEO
	 * 
	 * @return the value of PHOTOSANDVIDEOS.VIDEO
	 * 
	 * @mbggenerated
	 */
	public String getVideo() {
		return video;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PHOTOSANDVIDEOS.VIDEO
	 * 
	 * @param video
	 *            the value for PHOTOSANDVIDEOS.VIDEO
	 * 
	 * @mbggenerated
	 */
	public void setVideo(String video) {
		this.video = video == null ? null : video.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PHOTOSANDVIDEOS.SEQUENCE
	 * 
	 * @return the value of PHOTOSANDVIDEOS.SEQUENCE
	 * 
	 * @mbggenerated
	 */
	public Integer getSequence() {
		return sequence;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PHOTOSANDVIDEOS.SEQUENCE
	 * 
	 * @param sequence
	 *            the value for PHOTOSANDVIDEOS.SEQUENCE
	 * 
	 * @mbggenerated
	 */
	public void setSequence(Integer sequence) {
		this.sequence = sequence;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PHOTOSANDVIDEOS.CONFIGID
	 * 
	 * @return the value of PHOTOSANDVIDEOS.CONFIGID
	 * 
	 * @mbggenerated
	 */
	public Integer getConfigid() {
		return configid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PHOTOSANDVIDEOS.CONFIGID
	 * 
	 * @param configid
	 *            the value for PHOTOSANDVIDEOS.CONFIGID
	 * 
	 * @mbggenerated
	 */
	public void setConfigid(Integer configid) {
		this.configid = configid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PHOTOSANDVIDEOS.ISVIDEOORPHOTO
	 * 
	 * @return the value of PHOTOSANDVIDEOS.ISVIDEOORPHOTO
	 * 
	 * @mbggenerated
	 */
	public Integer getIsvideoorphoto() {
		return isvideoorphoto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PHOTOSANDVIDEOS.ISVIDEOORPHOTO
	 * 
	 * @param isvideoorphoto
	 *            the value for PHOTOSANDVIDEOS.ISVIDEOORPHOTO
	 * 
	 * @mbggenerated
	 */
	public void setIsvideoorphoto(Integer isvideoorphoto) {
		this.isvideoorphoto = isvideoorphoto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PHOTOSANDVIDEOS.UPDATETIME
	 * 
	 * @return the value of PHOTOSANDVIDEOS.UPDATETIME
	 * 
	 * @mbggenerated
	 */
	public Date getUpdatetime() {
		return updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PHOTOSANDVIDEOS.UPDATETIME
	 * 
	 * @param updatetime
	 *            the value for PHOTOSANDVIDEOS.UPDATETIME
	 * 
	 * @mbggenerated
	 */
	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PHOTOSANDVIDEOS.USERID
	 * 
	 * @return the value of PHOTOSANDVIDEOS.USERID
	 * 
	 * @mbggenerated
	 */
	public Integer getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PHOTOSANDVIDEOS.USERID
	 * 
	 * @param userid
	 *            the value for PHOTOSANDVIDEOS.USERID
	 * 
	 * @mbggenerated
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column PHOTOSANDVIDEOS.PHOTO
	 * 
	 * @return the value of PHOTOSANDVIDEOS.PHOTO
	 * 
	 * @mbggenerated
	 */
	public byte[] getPhoto() {
		return photo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column PHOTOSANDVIDEOS.PHOTO
	 * 
	 * @param photo
	 *            the value for PHOTOSANDVIDEOS.PHOTO
	 * 
	 * @mbggenerated
	 */
	public void setPhoto(byte[] photo) {
		this.photo = photo;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getImgval() {
		return Base64.encodeToString(photo);
	}

	public void setImgval(String imgval) {
		this.imgval = imgval;
	}

	public int getDeptid() {
		return deptid;
	}

	public void setDeptid(int deptid) {
		this.deptid = deptid;
	}

	public String getLocalURL() {
		return localURL;
	}

	public void setLocalURL(String localURL) {
		this.localURL = localURL;
	}

	// public int getDeptid() {
	// return deptid;
	// }
	//
	// public void setDeptid(int deptid) {
	// this.deptid = deptid;
	// }
}