package com.jrwp.wx.dao;

import com.jrwp.wx.entity.AppointmeInfo;
import com.jrwp.wx.entity.TimeQuan;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;

public interface AppointmeInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APPOINTME_INFO
     *
     * @mbggenerated
     */
    TimeQuan getTimequn(int id);

    List<AppointmeInfo> selectByopenidOrCardnumber(@Param("openid") String openid, @Param("cardnumber") String cardnumber,@Param("date") String date);

    AppointmeInfo getAppInfoByopenidOrCardnumber(@Param("openid") String openid, @Param("cardnumber") String cardnumber, @Param
            ("nowdate") Date date, @Param("deptid") int deptid);

    void cancleApp(int id);
    AppointmeInfo findByid(int id);

    int deleteByPrimaryKey(Integer id);

    int getTimequnCount(@Param("day") String day, @Param("time") int time, @Param("deptid") int deptid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APPOINTME_INFO
     *
     * @mbggenerated
     */
    int insert(AppointmeInfo record);

    int getAppCount(@Param("nowdate") Date date, @Param("deptid") Integer deptid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APPOINTME_INFO
     *
     * @mbggenerated
     */
    int insertSelective(AppointmeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APPOINTME_INFO
     *
     * @mbggenerated
     */
    AppointmeInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APPOINTME_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AppointmeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APPOINTME_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AppointmeInfo record);
}