package com.jrwp.wx.dao;

import com.jrwp.wx.entity.FrequentContacts;

import java.util.List;

public interface FrequentContactsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FREQUENT_CONTACTS
     *
     * @mbggenerated
     */
    int insert(FrequentContacts record);

    FrequentContacts getByCardNumber(String cardnumber);
    FrequentContacts getByid(int id);

    List<FrequentContacts> getByOpenid(String openid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FREQUENT_CONTACTS
     *
     * @mbggenerated
     */
    int insertSelective(FrequentContacts record);
}